[package]
name = "hypercube"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "26.0.0"
nalgebra = "0.33.2"
winit = "0.30.11"
env_logger = "0.11"
pollster = "0.4.0"
bytemuck = { version = "1.12", features = ["derive"] }
