[package]
name = "hypercube"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "0.20"
nalgebra = "0.32"
winit = "0.29"
env_logger = "0.11"
pollster = "0.3"
bytemuck = { version = "1.12", features = [ "derive" ] }
